name: dotnet-build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 6" # every Saturday

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]
    steps:
      - name: Calculate Fx version from dotnet-version
        run: |
          declare -A FxVersions
          FxVersions[3.1.x]=netcoreapp3.1
          FxVersions[6.0.x]=net6.0
          FxVersion=${FxVersions[${{matrix.dotnet-version}}]}
          echo Testing framework version:
          echo matrix.dotnet-version=${{matrix.dotnet-version}} 
          echo FxVersions=${FxVersions[@]}
          echo FxVersion=$FxVersion
          if [[ -z $FxVersion ]] ; then
            echo "Exiting: failed to set FxVersion"
            exit 1
          else
            echo "FxVersion=$FxVersion" >> $GITHUB_ENV
          fi          
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Dotnet Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test FxVersion
        run: dotnet test --framework ${{env.FxVersion}} --no-restore --verbosity normal /p:CollectCoverage=true
